### ISSUE TITLE
Issue while run of build.sh--- fatal error: cv_bridge/cv_bridge.h: No such file or directory

### ISSUE THREAD

**Issue by nguptaHQ** [abhineet123/ORB_SLAM2#11]
I am getting below error while running build.sh and not able to solve it.

Please help me.

**Configuring and building ORB_SLAM2 ...
mkdir: cannot create directory 'build': File exists
Build type: Release
-- Using flag -std=c++11.
-- Configuring done
-- Generating done
-- Build files have been written to: /abhineet123/ORB_SLAM2/build
Scanning dependencies of target ORB_SLAM2
[  8%] [  8%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/System.cc.o
Building CXX object CMakeFiles/ORB_SLAM2.dir/src/Tracking.cc.o
/abhineet123/ORB_SLAM2/src/Tracking.cc:39:33: fatal error: cv_bridge/cv_bridge.h: No such file or directory
 #include <cv_bridge/cv_bridge.h>
                                 ^
compilation terminated.
/abhineet123/ORB_SLAM2/src/System.cc:28:50: fatal error: boost/variant/detail/backup_holder.hpp: No such file or directory
 #include <boost/variant/detail/backup_holder.hpp>
                                                  ^
compilation terminated.
make[2]: *** [CMakeFiles/ORB_SLAM2.dir/src/Tracking.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/ORB_SLAM2.dir/src/System.cc.o] Error 1
make[1]: *** [CMakeFiles/ORB_SLAM2.dir/all] Error 2
make: *** [all] Error 2**

Thanks

**Comment by nguptaHQ** [comment]
Additional info:
I am trying to build this on Ubuntu using ./build.sh script.
cv_bridge is used for ROS Image message to OpenCv image.

I need to only make it for Ubuntu not ROS.

Please help.

**Comment by jahaniam** [comment]
This repo is through ROS. If you need ORB-SLAM itself it is better to clone form the original repo directly.

**Comment by nguptaHQ** [comment]
I installed ros kintetic in ubuntu and issue was resolved.
Thanks.

**Comment by Underquant** [comment]
> I installed ros kintetic in ubuntu and issue was resolved.
> Thanks.

Hi,  gangooteli and Ali, i met the same problem with you, but i still failed to compile after i install ros kinetic, could you give me some help?

**Comment by Underquant** [comment]
Hi, i solved this problems by adding the directory of ros into cmakelist.txt
`include_directories(
${PROJECT_SOURCE_DIR}
${PROJECT_SOURCE_DIR}/include
${EIGEN3_INCLUDE_DIR}
${Pangolin_INCLUDE_DIRS}
/opt/ros/kinetic/include
)
`

**Comment by jianzhuozhu** [comment]
> Hi, i solved this problems by adding the directory of ros into cmakelist.txt
> `include_directories( ${PROJECT_SOURCE_DIR} ${PROJECT_SOURCE_DIR}/include ${EIGEN3_INCLUDE_DIR} ${Pangolin_INCLUDE_DIRS} /opt/ros/kinetic/include ) `

useful!Thank you ,bro
